# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-11 21:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_html_output'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
